version: '3'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: C:\Users\angel\anlima\wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: C:\Users\angel\anlima\mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    expose:
      - "3306"
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"