version: '3'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/anlima/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/anlima/data/mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    restart: on-failure